baseURL = 'https://exarlab.com/'
languageCode = 'en-us'
title = 'Exar Labs LLC'

[params.homeInfoParams]
Title = "Welcome to Exar Labs LLC"
Content = "I'm Beric Bearnson and here I write about my life, interests, and projects."

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
