baseURL = 'https://exarlab.com/'
languageCode = 'en-us'
title = 'Exar Lab'

[params.homeInfoParams]
Title = "Welcome to Exar Lab"
Content = "I'm Beric Bearnson and here I write about my life, interests, and projects."

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
